"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$directory\
$git_branch\
$fill\
$python\
$kubernetes\
$line_break\
$character"""

palette = "catppuccin_mocha"

add_newline = true

[palettes.catppuccin_mocha]
rosewater = '#f5e0dc'
flamingo = '#f2cdcd'
pink = '#f5c2e7'
mauve = '#cba6f7'
red = '#f38ba8'
maroon = '#eba0ac'
peach = '#fab387'
yellow = '#f9e2af'
green = '#a6e3a1'
teal = '#94e2d5'
sky = '#89dceb'
sapphire = '#74c7ec'
blue = '#89b4fa'
lavender = '#b4befe'
text = '#cdd6f4'
subtext1 = '#bac2de'
subtext0 = '#a6adc8'
overlay2 = '#9399b2'
overlay1 = '#7f849c'
overlay0 = '#6c7086'
surface2 = '#585b70'
surface1 = '#45475a'
surface0 = '#313244'
base = '#1e1e2e'
mantle = '#181825'
crust = '#11111b'

[username]
show_always = true
style_root = 'fg:base bg:red bold'
style_user = 'fg:base bg:mauve bold'
format = '[  $user ]($style)'

[directory]
truncation_length = 3
truncate_to_repo = false
style = 'fg:text bg:surface0'
format = '[  $path ]($style)[](fg:surface0 bg:base)'

[git_branch]
symbol = ' '
style = 'fg:base bg:lavender bold'
format = "[ $symbol$branch ]($style)[](fg:lavender bg:base)"

# INFO: The 'git_status' module is very slow on windows directories, so we will just disable it
[git_status]
disabled = true

[fill]
symbol = " "

[python]
symbol = ' '
style = 'fg:yellow bold bg:surface0'
format = '[ $symbol$version ]($style)'
python_binary = "python3"

[kubernetes]
disabled = false
symbol = '󱃾 '
style = 'fg:base bg:blue bold'
format = '[ $symbol$context ]($style)'

[line_break]
disabled = false

[character]
success_symbol = '[❯](bold lavender)'
error_symbol = '[❯](bold red)'
